version: '3'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "$JAM_API_PORT:$JAM_API_PORT"
    volumes:
    - '$JAM_DATA_DIR:$JAM_DATA_DIR'
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
