version: '3'

services:
  jamfactory:
    build: ./Dockerfile-prod
    ports:
      - $JAM_API_PORT:3000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
