version: '3'

services:
  app:
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - $JAM_API_PORT:$JAM_API_PORT
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
