version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    environment:
      - "JAM_PRODUCTION=PRODUCTION"
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - './data:$JAM_DATA_DIR'
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
