version: '3.1'

services:

  jamfactory:
    build: .
    ports:
      - 3000:3000
    environment:
      SPOTIFY_ID: ""
      SPOTIFY_SECRET: ""
      SPOTIFY_REDIRECT_URL: "http://localhost:3000/auth/callback"
      MONGO_DB: "mongodb://mongo:27017"
      MONGO_DB_NAME: "jamfactory"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
