version: '3'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
    - './data:$JAM_DATA_DIR'
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
