version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file: .env
    environment:
      JAM_DATA_DIR: /data
      JAM_REDIS_ADDRESS: redis:6379
    ports:
      - '3000:3000'
    volumes:
      - "jam-data:/data"
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  jam-data:
