version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file:
      - .env
    ports:
      - $JAM_API_PORT:$JAM_API_PORT
    restart: always
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
