version: '3.1'

services:

  jamfactory:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - 6379:6379

networks:
  default:
    external:
      name: jamfactory
