# golang:1.14-alpine
FROM golang@sha256:032054b7b190502c52862bb51e2f6d7e71f4cd47e2d03ce82b4980c6cf212cf0 as builder

RUN apk update \
    && apk add --no-cache git ca-certificates tzdata \
    && update-ca-certificates

WORKDIR $GOPATH/src/github.com/jamfactoryapp/jamfactory-backend

COPY go.mod .
RUN go mod download
RUN go mod verify

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags='-w -s -extldflags "-static"' \
    -a -o /go/bin/jamfactory-backend .

# scratch
FROM scratch

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

COPY --from=builder /go/bin/jamfactory-backend /go/bin/jamfactory-backend

ENTRYPOINT ["/go/bin/jamfactory-backend"]
