version: '3.1'

services:

  jamfactory:
    build: ./Dockerfile-prod
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
    restart: always

networks:
  default:
    external:
      name: jamfactory
