version: '3.1'

services:

  jamfactory:
    build: .
    ports:
      - 3000:3000
    environment:
      SPOTIFY_ID: "91c10e68700f4b34b09950bc350de507"
      SPOTIFY_SECRET: "24e342ee665c4aa991ff3dae2a15ef36"
      SPOTIFY_REDIRECT_URL: "http://localhost:3000/api/v1/auth/callback"
      REDIS_ADDRESS: "redis:6379"
      REDIS_DATABASE: "0"
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

networks:
  default:
    external:
      name: jamfactory
